      SUBROUTINE errhdr
      IMPLICIT NONE
C-----------------------------------------------------------------------
c     print a header in the error file to denote that this error was
c     generated by a particular hidden run from the sliding spans or
c     revision history analysis.
C-----------------------------------------------------------------------
      INCLUDE 'srslen.prm'
      INCLUDE 'notset.prm'
      INCLUDE 'ssap.prm'
      INCLUDE 'ssft.cmn'
      INCLUDE 'rev.prm'
      INCLUDE 'rev.cmn'
      INCLUDE 'hiddn.cmn'
      INCLUDE 'units.cmn'
C-----------------------------------------------------------------------
      CHARACTER dash*(1),star*(1)
      INTEGER i
c-----------------------------------------------------------------------
      DATA dash,star/'-','*'/
c-----------------------------------------------------------------------
      IF(Issap.lt.2.and.Irev.lt.4)RETURN
      IF((Issap.eq.2.and.Ierhdr.eq.Icol).or.
     &   (Irev.eq.4.and.Ierhdr.eq.Revptr))RETURN
C-----------------------------------------------------------------------
      IF(Issap.eq.2)THEN
       WRITE(Mt2,1010)(star,dash,i=1,40)
       WRITE(Mt2,1020)Icol
       Ierhdr=Icol
      ELSE IF(Issap.eq.3.and.Ierhdr.ne.NOTSET)THEN
       WRITE(Mt2,1010)(star,dash,i=1,40)
       WRITE(Mt2,1040)' '
       Ierhdr=NOTSET
      ELSE IF(Irev.eq.4)THEN
       WRITE(Mt2,1010)(star,dash,i=1,40)
       WRITE(Mt2,1030)Crvend(1:Nrvend)
       Ierhdr=Revptr
      ELSE IF(Irev.eq.5.and.Ierhdr.ne.NOTSET)THEN
       WRITE(Mt2,1010)(star,dash,i=1,40)
       WRITE(Mt2,1040)' '
       Ierhdr=NOTSET
      END IF
C-----------------------------------------------------------------------
 1010 FORMAT(80A1)
 1020 FORMAT('  Error/Warning Messages for sliding span # ',i1,':')
 1030 FORMAT('  Error/Warning Messages for history run ending ',a,':')
 1040 FORMAT(A)
      RETURN
      END
      